

quarkus:
  sco:
    connector:
      definitions:
        - name: "${quarkus.sco.connector.type}-source-${quarkus.sco.connector.version}"
          description: "Query data from a  Amazon Redshift Database."
          title: ' Amazon Redshift source'
          source:
            name: 'connector-${quarkus.sco.connector.type}-source'
          sink:
            name: 'connector-kafka-sink'
        - name: "${quarkus.sco.connector.type}-sink-${quarkus.sco.connector.version}"
          description: "Send data to a  Amazon Redshift Database."
          title: ' Amazon Redshift sink'
          source:
            name: 'connector-kafka-source'
          sink:
            name: 'connector-${quarkus.sco.connector.type}-sink'