

quarkus:
  sco:
    connector:
      definitions:
        - name: "${quarkus.sco.connector.type}-source-${quarkus.sco.connector.version}"
          description: "Receive data from an Amazon S3 bucket."
          title: 'Amazon S3 source'
          source:
            name: 'connector-${quarkus.sco.connector.type}-source'
          sink:
            name: 'connector-kafka-sink'
        - name: "${quarkus.sco.connector.type}-sink-${quarkus.sco.connector.version}"
          description: "Send data to an Amazon S3 bucket."
          title: 'Amazon S3 sink'
          source:
            name: 'connector-kafka-source'
          sink:
            name: 'connector-${quarkus.sco.connector.type}-sink'