apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: connector-jms-apache-artemis-sink
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.version: "${quarkus.sco.kamelets.version}"
  labels:
    camel.apache.org/kamelet.type: "sink"
    camel.apache.org/requires.runtime: camel-k
spec:
  definition:
    title: "JMS - Apache Artemis Kamelet Sink"
    description: "Send data to an Apache Artemis message broker by using JMS."
    required:
      - destinationName
      - brokerURL
    type: object
    properties:
      destinationType:
        title: "Destination Type"
        description: "The JMS destination type (queue or topic)."
        type: string
        default: queue
      destinationName:
        title: "Destination Name"
        description: "The JMS destination name."
        type: string
      brokerURL:
        title: "Broker URL"
        description: "The JMS URL."
        type: string
        example: "tcp://my-host:61616"
  dependencies:
  - "camel:jms"
  - "camel:kamelet"
  template:
    beans:
      - name: "local-cf"
        type: "#class:org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory"
        properties:
          brokerURL: '{{brokerURL}}'
    from:
      uri: "kamelet:source"
      steps:
      - to:
          uri: "jms:{{destinationType}}:{{destinationName}}"
          parameters:
            connectionFactory: "#bean:{{local-cf}}"
