

quarkus:
  sco:
    connector:
      definitions:
        - name: "${quarkus.sco.connector.type}-sink-${quarkus.sco.connector.version}"
          description: "Send data to Amazon CloudWatch metrics."
          title: 'Amazon CloudWatch Metrics sink'
          source:
            name: 'connector-kafka-source'
          sink:
            name: 'connector-${quarkus.sco.connector.type}-sink'