apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: connector-jms-amqp-10-source
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.version: "${quarkus.sco.kamelets.version}"
  labels:
    camel.apache.org/kamelet.type: "source"
    camel.apache.org/requires.runtime: camel-k
spec:
  definition:
    title: "JMS - AMQP 1.0 Kamelet Source"
    description: "Consume data from any AMQP 1.0 compliant message broker by using the Apache Qpid JMS client."
    required:
      - destinationName
      - brokerURL
    type: object
    properties:
      destinationType:
        title: "Destination Type"
        description: "The JMS destination type (queue or topic)."
        type: string
        default: queue
      destinationName:
        title: "Destination Name"
        description: "The JMS destination name."
        type: string
      brokerURL:
        title: "Broker URL"
        description: "The JMS URL."
        type: string
        example: "amqp://my-host:31616"
  dependencies:
  - "camel:jms"
  - "camel:kamelet"
  template:
    beans:
      - name: "local-cf"
        type: "#class:org.apache.qpid.jms.JmsConnectionFactory"
        properties:
          remoteURI: '{{brokerURL}}'
    from:
      uri: "jms:{{destinationType}}:{{destinationName}}"
      parameters:
        connectionFactory: "#bean:{{local-cf}}"
      steps:
      - to:
          uri: "kamelet:sink"
