

quarkus:
  sco:
    connector:
      definitions:
        - name: "${quarkus.sco.connector.type}-source-${quarkus.sco.connector.version}"
          description: "Retrieve data by sending a query to an Apache Cassandra cluster table."
          title: 'Apache Cassandra source'
          source:
            name: 'connector-cassandra-source'
          sink:
            name: 'connector-kafka-sink'
        - name: "${quarkus.sco.connector.type}-sink-${quarkus.sco.connector.version}"
          description: "Send data to an Apache Cassandra cluster."
          title: 'Apache Cassandra sink'
          source:
            name: 'connector-kafka-source'
          sink:
            name: 'connector-${quarkus.sco.connector.type}-sink'