

quarkus:
  sco:
    connector:
      definitions:
        - name: "${quarkus.sco.connector.type}-sink-${quarkus.sco.connector.version}"
          description: "Send email through the Amazon Simple Email Service (SES)."
          title: 'Amazon Simple Email Service sink'
          source:
            name: 'connector-kafka-source'
          sink:
            name: 'connector-${quarkus.sco.connector.type}-sink'