

quarkus:
  sco:
    connector:
      definitions:
        - name: "${quarkus.sco.connector.type}-source-${quarkus.sco.connector.version}"
          description: "Send messages to Google Pubsub."
          title: 'Google Cloud Storage source'
          source:
            name: 'connector-${quarkus.sco.connector.type}-source'
          sink:
            name: 'connector-kafka-sink'
        - name: "${quarkus.sco.connector.type}-sink-${quarkus.sco.connector.version}"
          description: "Upload data to Google Cloud Storage."
          title: 'Google Cloud Storage sink'
          source:
            name: 'connector-kafka-source'
          sink:
            name: 'connector-${quarkus.sco.connector.type}-sink'