name: Build Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - "LICENSE"
      - "**/.gitignore"
      - "**.md"
      - "**.adoc"
      - "*.txt"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/build-tag.yaml"
      - ".github/workflows/build-it.yaml"
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx3000m
  MAVEN_ARGS: -V -ntp -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -e
  CONNECTORS_DIR: etc/kubernetes/manifests/base
  PROJECTS: ${{ github.workspace }}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: sco-connector

      - name: "Checkout sco-manifests project"
        uses: actions/checkout@v3
        with:
          repository: sco1237896/sco-manifests
          token: ${{ secrets.GITHUB_TOKEN }}
          path: sco-manifests

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set versions
        run: |
          export C_VERSION="${GITHUB_REF_NAME#v}" 
          export C_REVISION="${GITHUB_SHA}" 
          
          echo "CONNECTORS_VERSION=${C_VERSION}" >> $GITHUB_ENV
          echo "CONNECTORS_REVISION=${C_REVISION}" >> $GITHUB_ENV
          echo "CONNECTORS_RELEASE=${C_VERSION}-${C_REVISION}" >> $GITHUB_ENV
      - name: Build Project
        run: |          
          cd ${{ env.PROJECTS }}/sco-connector
          
          ./mvnw ${MAVEN_ARGS} clean install -U \
            -Pcontainer-test \
            -Dconnector.catalog.root=${{ env.PROJECTS }}/sco-manifests/connectors \
            -Dconnector.container.tag=${CONNECTORS_RELEASE} \
            -Dlog.enabled=true

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Push Container Images
        run: |
          echo "Pushing container images"
          echo "Pushing container images"
          
          IMAGES=$(docker image ls --format "{{.Repository}}:{{.Tag}}" | grep quay.io/sco1237896/connector- | grep ${CONNECTORS_RELEASE} || :;)
          
          echo "Images[@]: ${IMAGES[@]}"
          echo "Images: ${IMAGES}"
          
          for IMAGE in ${IMAGES}; do
              echo "Pushing image: ${IMAGE}"
              docker push $IMAGE
          done

      - name: "Create PR for sco-connector"
        env:
          BRANCH_NAME: "sco-connector.${{ env.CONNECTORS_RELEASE }}"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ""
          echo "tag      : ${{ github.ref_name }}"
          echo "version  : ${CONNECTORS_VERSION}"
          echo "revision : ${CONNECTORS_REVISION}"
          echo "release  : ${CONNECTORS_RELEASE}"
          echo "branch   : ${BRANCH_NAME}"
          echo ""

          cd ${{ env.PROJECTS }}/sco-manifests

          ls -lR connectors

          git config user.email "sco-connectors@sco1237896.github.com"
          git config user.name "sco-connectors"

          git checkout -b ${BRANCH_NAME}
          git add connectors
          git status

          if [ -z "$(git status --untracked-files=no --porcelain connectors)" ]; then
            echo "Working directory clean excluding untracked files"
          else
            git commit -m "Update connectors" connectors
            git reset --hard
            git push -u origin ${BRANCH_NAME}

            # GH CLI can't find the branch on remote... needs some time :)
            sleep 15

            gh config set prompt disabled

            gh pr create \
              --fill \
              --base main \
              --title "chore(catalog): update connectors to ${{ env.CONNECTORS_RELEASE }}" \
              --body "sha: ${{ github.sha }}, tag: ${{ github.ref_name }}"
          fi
